version: '2.4'

services:

  radarr:
    image: stlouisn/radarr:latest
    container_name: radarr
    hostname: radarr
    restart: always
    volumes:
      - /docker/radarr/config:/config
      - /media/downloads:/downloads
      - /media/movies:/movies
    mem_limit: 500M
    memswap_limit: 500M
    logging:
      driver: json-file
        options:
          max-size: "10M"
          max-file: "3"
    ports:
      - 7878
